# Executable names:
EXE = lab_ml
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = graph.o main.o Network.o file_bot.o landmark.o priorityqueue.o dijkstraSSSP.o


# Use the cs225 makefile template:
include cs225/make/cs225.mk