# Executable names:
EXE = network
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = cs225/HSLAPixel.o cs225/PNG.o cs225/lodepng/lodepng.o graph.o main.o Network.o file_bot.o landmark.o priorityqueue.o dijkstraSSSP.o BFS.o graphvis.o 


# Use the cs225 makefile template:
include cs225/make/cs225.mk